### PR TITLE
Update day4.md

### PR DESCRIPTION
**Pull request by jabbink**
Line 32: "it is required to comply with all rule and strategy names literally"

So I changed BinOp en UnOp further down to Bop and Uop.

### CODE REVIEW

**Comment by Gohla** [comment]
@eduardosamorim Can this be merged?

**Comment by udesou** [comment]
I think the students used BinOp and UnOp.

**Comment by Gohla** [comment]
Ok, then Uop and Bop should be changed to UnOp and BinOp in the Objectives section.

**Comment by guwac** [comment]
@eduardosamorim Was this fixed?
@jabbink: 2 bonus points for pointing out the inconsistency.

**Comment by udesou** [comment]
@guwac I guess so. As I said, I think the students used BinOp and UnOp, but I thought the lab description was already correct (because they followed it).

**Comment by guwac** [comment]
There was another inconsistency. `UnOp` and `BinOp` should be the sorts of new constructors for operators, and `UnExp` and `BinExp` should be new constructors for sort `Exp`.

**Pull request closed without merging**
